###{SERVER
server.port=8080
###

### DB {
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=mydb
spring.datasource.password=mydb
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver
# حداکثر زمان برای اتصال‌های بی‌استفاده به DB عملیات به میلی ثانبه
spring.datasource.hikari.idle-timeout=900000
#حداکثر اتصال‌های همزمانی که میتوان به DB عملیات داشت.
# برای عدم محدودیت می تواند از صفر یا اعداد منفی استفاده شود
spring.datasource.hikari.maximum-pool-size=200
# زمان انتظار برای دریافت اتصال به DB عملیات. پس از این زمان، خطای timeout رخ میدهد. واحد آن میلی ثانیه است.
spring.datasource.hikari.connection-timeout=6000
# حداقل اتصالهایی که میتوان به هر پارتیشن DB عملیات داشت.
spring.datasource.hikari.minimum-idle=5
#حد اکثر زمان کلی اعتبار یک connection در DB عملیاتی. (شامل زمان های idle و in-use) به میلی ثانیه
spring.datasource.hikari.max-lifetime=43200000
# حداکثر زمان انتظار برای انجام عملیات یک تراکنش
spring.transaction.default-timeout=600s
spring.jpa.open-in-view=false
###} DB
###{SECURITY
security.jwt.expiration-time=1h
security.jwt.secret-key=Y2hhbmdlLW1lLWNoYW5nZS1tZS1jaGFuZ2UtbWUtY2hhbmdlLW1lLWNoYW5nZS1tZS1jaGFuZ2UtbWU=
###}
###{SIGNUP
signup.ticket.template-id=123456
signup.ticket.length=4
signup.ticket.time-to-live=2m
signup.ticket.block-duration=2m
signup.ticket.max-failure-count=5
signup.token-ttl=2m
###}
###{SMS
sms.api-key=2d2Oox8IDA69FRMfCjOokDKmsgUazaNSOrZGIUxja4DcL2yc
sms.base-url=https://api.sms.ir
###}
###{SHAHKAR
shahkar.base-url=https://service.zohal.io/api/v0
shahkar.token=853371acb8216166e6d8bc8352ae8923ef582a44
###}

###### Cache Config ######
####{ Redis Common Config
# در صورت فعال بودن این تنظیم از کش ردیس استفاده می شود
tedisson.redis.enabled=false
# نوع ارتباط با ردیس که می تواند مقادیر زیر باشد
#single_node, cluster, sentinel, master_slave
tedisson.redis.connection-type=single_node
# نام کاربری اتصال به ردیس
tedisson.redis.username=
# بازه زمانی به میلی ثانیه که با دستور ping کانکشن چک می شود و باز نگه داشته می شود
tedisson.redis.ping-connection-interval=10000
# حداکثر مدت زمان برای برقراری ارتباط با سرور ردیس به میلی ثانیه
tedisson.redis.connect-timeout=10000
# تعداد اشتراک به ازای هر کانکشن
tedisson.redis.subscriptions-per-connection=5
# نوع کش استفاده شده در حالت لوکال
tedisson.local.cache-provider=caffeine
####} Redis Common Config
####{ Redis Single Node Config
# آدرس آیپی و پورت ردیس در حالت تک سرور به صورت زیر
# IP:Port
tedisson.redis.single-server.address=localhost:10501
# شماره دیتابیس در حالت تک سرور
tedisson.redis.single-server.database=2
# حداقل تعداد کانکشن ها در حالت بیکار
tedisson.redis.single-server.connection-minimum-idle-size=24
# تعداد کانکشن ها
tedisson.redis.single-server.connection-pool-size=64
# حداقل تعداد کانکشن های اشتراکی بیکار
tedisson.redis.single-server.subscription-connection-minimum-idle-size=5
# تعداد کانکشن های اشتراکی
tedisson.redis.single-server.subscription-connection-pool-size=50
####} Redis Single Node Config
####{ Redis Cluster Config
# آدرس گره های master در کلاستر که با , جدا می شوند و با فرمت IP:Port می باشد
tedisson.redis.cluster-servers.node-addresses=
# نوع خواندن که می تواند شامل مقادیر زیر باشد
# master, slave, master_slave
tedisson.redis.cluster-servers.read-mode=master
# نوع اشتراک که می تواند شامل مقادیر زیر باشد
tedisson.redis.cluster-servers.subscription-mode=master
# حداقل تعداد کانکشن های master در حالت بیکار
tedisson.redis.cluster-servers.master-connection-minimum-idle-size=24
# تعداد کانکشن های master
tedisson.redis.cluster-servers.master-connection-pool-size=64
# تعداد کانکشن های slave
tedisson.redis.cluster-servers.slave-connection-pool-size=64
# حداقل تعداد کانکشن های slave در حالت بیکار
tedisson.redis.cluster-servers.slave-connection-minimum-idle-size=24
# حداقل تعداد کانکشن های اشتراکی بیکار
tedisson.redis.cluster-servers.subscription-connection-minimum-idle-size=5
# تعداد کانکشن های اشتراکی
tedisson.redis.cluster-servers.subscription-connection-pool-size=50
# مدت زمان جست و جوی کلاستر به میلی ثانیه
tedisson.redis.cluster-servers.scan-interval=5000
# مدت زمان بررسی end point های dns
# با مقدار -1 غیر فعال می شود
tedisson.redis.cluster-servers.dns-monitoring-interval=5000
# در صورت اتفاق افتادن خطا در اجرای دستور بعد از این مدت زمان slave از لیست گره های در دسترس خارج می شود
tedisson.redis.cluster-servers.failed-slave-check-interval=180000
# بعد از حذف شدن slave از لیست در دسترس با فاصله این تنظیم مجددا تلاش برای برقراری ارتباط مجدد انجام می شود
tedisson.redis.cluster-servers.failed-slave-reconnection-interval=3000
####} Redis Cluster Config
####{ Redis Sentinel Config
# شماره دیتابیس
tedisson.redis.sentinel-servers.database=2
# نام کاربری sentinel
tedisson.redis.sentinel-servers.sentinel-username=
# کلمه عبور sentinel
tedisson.redis.sentinel-servers.sentinel-password=
# آدرس گره های sentinel که با , جدا می شوند و با فرمت IP:Port می باشد
tedisson.redis.sentinel-servers.sentinel-addresses=
# نام master
tedisson.redis.sentinel-servers.master-name=
# نوع گره ای که از آن خواندن انجام می شود و می تواند مقادیر زیر باشد
# master, slave, master_slave
tedisson.redis.sentinel-servers.read-mode=master
# نوع گره ای که اشتراک در آن انجام می شود و می تواند مقادیر زیر باشد
# master, slave
tedisson.redis.sentinel-servers.subscription-mode=master
# حداقل تعداد کانکشن های master در حالت بیکار
tedisson.redis.sentinel-servers.master-connection-minimum-idle-size=24
# تعداد کانکشن های master
tedisson.redis.sentinel-servers.master-connection-pool-size=64
# حداقل تعداد کانکشن های slave در حالت بیکار
tedisson.redis.sentinel-servers.slave-connection-minimum-idle-size=24
# تعداد کانکشن های slave
tedisson.redis.sentinel-servers.slave-connection-pool-size=64
# حداقل تعداد کانکشن های اشتراکی بیکار
tedisson.redis.sentinel-servers.subscription-connection-minimum-idle-size=5
# تعداد کانکشن های اشتراکی
tedisson.redis.sentinel-servers.subscription-connection-pool-size=50
# مدت زمان جست و جوی sentinel به میلی ثانیه
tedisson.redis.sentinel-servers.scan-interval=1000
# چک کردن لیست sentinel در زمان راه اندازی
tedisson.redis.sentinel-servers.check-sentinels-list=true
# چک کردن وضعیت slave ها
tedisson.redis.sentinel-servers.check-slave-status-with-syncing=true
# در صورت اتفاق افتادن خطا در اجرای دستور بعد از این مدت زمان slave از لیست گره های در دسترس خارج می شود
tedisson.redis.sentinel-servers.failed-slave-check-interval=180000
# بعد از حذف شدن slave از لیست در دسترس با فاصله این تنظیم مجددا تلاش برای برقراری ارتباط مجدد انجام می شود
tedisson.redis.sentinel-servers.failed-slave-reconnection-interval=3000
# فعال بودن جست و جو در sentinel
tedisson.redis.sentinel-servers.sentinels-discovery=true
# مدت زمان بررسی end point های dns
# با مقدار -1 غیر فعال می شود
tedisson.redis.sentinel-servers.dns-monitoring-interval=5000
####{ Redis Master Slave Config
# شماره دیتابیس
tedisson.redis.master-slave-servers.database=2
# نوع گره ای که از آن خواندن انجام می شود و می تواند مقادیر زیر باشد
# master, slave, master_slave
tedisson.redis.master-slave-servers.read-mode=master
# نوع گره ای که اشتراک در آن انجام می شود و می تواند مقادیر زیر باشد
# master, slave
tedisson.redis.master-slave-servers.subscription-mode=master
# آدرس گره master با فرمت IP:Port
tedisson.redis.master-slave-servers.master-address=
# آدرس گره های slave که با , جدا می شوند و با فرمت IP:Port می باشد
tedisson.redis.master-slave-servers.slave-addresses=
# حداقل تعداد کانکشن های master در حالت بیکار
tedisson.redis.master-slave-servers.master-connection-minimum-idle-size=24
# تعداد کانکشن های master
tedisson.redis.master-slave-servers.master-connection-pool-size=64
# حداقل تعداد کانکشن های slave در حالت بیکار
tedisson.redis.master-slave-servers.slave-connection-minimum-idle-size=24
# تعداد کانکشن های slave
tedisson.redis.master-slave-servers.slave-connection-pool-size=64
# حداقل تعداد کانکشن های اشتراکی بیکار
tedisson.redis.master-slave-servers.subscription-connection-minimum-idle-size=5
# تعداد کانکشن های اشتراکی
tedisson.redis.master-slave-servers.subscription-connection-pool-size=50
# در صورت اتفاق افتادن خطا در اجرای دستور بعد از این مدت زمان slave از لیست گره های در دسترس خارج می شود
tedisson.redis.master-slave-servers.failed-slave-check-interval=180000
# بعد از حذف شدن slave از لیست در دسترس با فاصله این تنظیم مجددا تلاش برای برقراری ارتباط مجدد انجام می شود
tedisson.redis.master-slave-servers.failed-slave-reconnection-interval=3000
####} Redis Master Slave Config
