-- =============================================================================
-- V2 : Product catalog
-- Media, Category, Brand, Product and their child collection tables.
-- =============================================================================

CREATE SEQUENCE MEDIA_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE MEDIA
(
    ID BIGINT NOT NULL DEFAULT NEXTVAL('media_seq'),

    CONSTRAINT PK_MEDIA PRIMARY KEY (ID)
);

CREATE TABLE MEDIA_IMAGE
(
    MEDIA_ID   BIGINT       NOT NULL,
    SORT_ORDER INTEGER      NOT NULL,
    IMAGE_URL  VARCHAR(1024) NOT NULL,

    CONSTRAINT PK_MEDIA_IMAGE PRIMARY KEY (MEDIA_ID, SORT_ORDER),
    CONSTRAINT FK_MEDIA_IMAGE_MEDIA FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA (ID) ON DELETE CASCADE
);

CREATE SEQUENCE CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE CATEGORY
(
    ID            BIGINT       NOT NULL DEFAULT NEXTVAL('category_seq'),
    NAME          VARCHAR(255) NOT NULL,
    PARENT_ID     BIGINT,
    LOCAL_NAME    VARCHAR(255),
    LOGO_MEDIA_ID BIGINT,

    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_CATEGORY_LOGO_MEDIA FOREIGN KEY (LOGO_MEDIA_ID) REFERENCES MEDIA (ID)
);

CREATE SEQUENCE BRAND_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE BRAND
(
    ID            BIGINT       NOT NULL DEFAULT NEXTVAL('brand_seq'),
    NAME          VARCHAR(255) NOT NULL,
    LOCAL_NAME    VARCHAR(255),
    MANUFACTURER  VARCHAR(255),
    LOGO_MEDIA_ID BIGINT,
    COUNTRY       VARCHAR(255),

    CONSTRAINT PK_BRAND PRIMARY KEY (ID),
    CONSTRAINT FK_BRAND_LOGO_MEDIA FOREIGN KEY (LOGO_MEDIA_ID) REFERENCES MEDIA (ID)
);

CREATE SEQUENCE PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE PRODUCT
(
    ID                BIGINT       NOT NULL DEFAULT NEXTVAL('product_seq'),
    CODE              VARCHAR(100) NOT NULL,
    CATEGORY_ID       BIGINT       NOT NULL,
    SUB_CATEGORY_ID   BIGINT,
    URL               VARCHAR(255) NOT NULL,
    SHORT_DESCRIPTION VARCHAR(1024),
    FULL_DESCRIPTION  TEXT,
    SPECIFICATION     JSONB,
    IMAGE_ALT_TEXT    VARCHAR(255),
    IMAGE_MEDIA_ID    BIGINT,
    NAME              VARCHAR(255) NOT NULL,
    LOCAL_NAME        VARCHAR(255),
    BRAND_ID          BIGINT,
    INVENTORY_STATUS  VARCHAR(32)  NOT NULL,
    STATUS            VARCHAR(32)  NOT NULL,
    INVENTORY_COUNT   INTEGER      NOT NULL DEFAULT 0,
    CREATED_AT        TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT        TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT UK_PRODUCT_CODE UNIQUE (CODE),
    CONSTRAINT UK_PRODUCT_URL UNIQUE (URL),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_PRODUCT_SUB_CATEGORY FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_PRODUCT_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID),
    CONSTRAINT FK_PRODUCT_IMAGE_MEDIA FOREIGN KEY (IMAGE_MEDIA_ID) REFERENCES MEDIA (ID)
);

CREATE TABLE PRODUCT_PRICE
(
    PRODUCT_ID     BIGINT        NOT NULL,
    PRICE          NUMERIC(12, 2) NOT NULL,
    DISCOUNT_PRICE NUMERIC(12, 2),
    VARIANT_TYPE   VARCHAR(64)   NOT NULL,

    CONSTRAINT FK_PRODUCT_PRICE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);
