-- =============================================================================
-- V5 : Replace media-reference image columns with base64 storage
-- =============================================================================

ALTER TABLE PRODUCT
    DROP CONSTRAINT IF EXISTS FK_PRODUCT_IMAGE_MEDIA,
    DROP CONSTRAINT IF EXISTS FK_PRODUCT_OTHER_IMAGE_MEDIA,
    DROP COLUMN IF EXISTS IMAGE_ALT_TEXT,
    DROP COLUMN IF EXISTS IMAGE_MEDIA_ID,
    DROP COLUMN IF EXISTS OTHER_IMAGE_ALT_TEXT,
    DROP COLUMN IF EXISTS OTHER_IMAGE_MEDIA_ID;

ALTER TABLE PRODUCT
    ADD COLUMN MAIN_IMAGE_ALT_TEXT VARCHAR(255),
    ADD COLUMN MAIN_IMAGE_DATA     TEXT;

CREATE TABLE PRODUCT_OTHER_IMAGE
(
    PRODUCT_ID BIGINT      NOT NULL,
    ALT_TEXT   VARCHAR(255),
    IMAGE_DATA TEXT        NOT NULL,
    CONSTRAINT FK_PRODUCT_OTHER_IMAGE FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);
