-- =============================================================================
-- V1.6 : Shopping cart
-- A single active cart per user, with one row per (product, variant) line item.
-- =============================================================================

-- Hibernate allocationSize = 50, so the sequences must increment by 50.
CREATE SEQUENCE CART_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE CART
(
    ID         BIGINT    NOT NULL DEFAULT NEXTVAL('cart_seq'),
    USER_ID    BIGINT    NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_CART PRIMARY KEY (ID),
    CONSTRAINT UK_CART_USER UNIQUE (USER_ID),
    CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID) ON DELETE CASCADE
);

CREATE SEQUENCE CART_ITEM_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE CART_ITEM
(
    ID             BIGINT         NOT NULL DEFAULT NEXTVAL('cart_item_seq'),
    CART_ID        BIGINT         NOT NULL,
    PRODUCT_ID     BIGINT         NOT NULL,
    VARIANT_TYPE   VARCHAR(64)    NOT NULL,
    QUANTITY       INTEGER        NOT NULL,
    UNIT_PRICE     NUMERIC(12, 2) NOT NULL,
    DISCOUNT_PRICE NUMERIC(12, 2),
    CREATED_AT     TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT     TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_CART_ITEM PRIMARY KEY (ID),
    CONSTRAINT UK_CART_ITEM_PRODUCT_VARIANT UNIQUE (CART_ID, PRODUCT_ID, VARIANT_TYPE),
    CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CART (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);
